apiVersion: project.migrx.io/v1alpha1
kind: ProjectSet
metadata:
  annotations:
    app.kubernetes.io/name: projectset
  name: devteam-projectset2
spec:
  namespace: dev-app
  labels:
    app: frontend
    stage: dev2
  annotations:
    app.kubernetes.io/name: dev-app
    app.kubernetes.io/lang: golang
  template: dev-small
        