apiVersion: project.migrx.io/v1alpha1
kind: ProjectSetTemplate
metadata:
  labels:
    app.kubernetes.io/name: projectsettemplate
    app.kubernetes.io/instance: dev-small
    app.kubernetes.io/part-of: projectset-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: projectset-operator
  name: dev-mid
spec:

  labels:
    stage: dev-from-template
    env: dev
  annotations:
    app.kubernetes.io/template: dev-mid

  limitRange:
    limits:
      - default:
          cpu: 500m
          memory: "50Mi"
        defaultRequest:
          cpu: 500m
          memory: "50Mi"
        max:
          cpu: "1"
          memory: "4Gi"
        min:
          cpu: 100m
          memory: "50Mi"
        type: Container


  roleRules:
    developer:
      - apiGroups:
          - ""
          - apps
        resources:
          - configmaps
          - deployments
          - pods
          - pods/log
        verbs: ["*"]

  groupPermissions:
    developer:
      - kind: "Group"
        name: "developer"
