apiVersion: project.migrx.io/v1alpha1
kind: ProjectSetTemplate
metadata:
  annotations:
    app.kubernetes.io/name: projectsettemplate
  name: dev-small
spec:

  labels:
    template: dev-small
    stage: dev

  annotations:
    app.kubernetes.io/template: dev-small
    app.kubernetes.io/stage: dev

  resourceQuota:
    hard:
      requests.cpu: "1"
      requests.memory: 1Gi
      limits.cpu: "2"
      limits.memory: 2Gi

  limitRange:
    limits:
      - default:
          cpu: 500m
          memory: "50Mi"
        defaultRequest:
          cpu: 500m
          memory: "50Mi"
        max:
          cpu: "2"
          memory: "2Gi"
        min:
          cpu: 100m
          memory: "50Mi"
        type: Container

  roles:
    developer:
      - apiGroups:
          - ""
        resources:
          - configmaps
          - pods
        verbs: ["*"]
    admin:
      - apiGroups:
          - ""
          - apps
        resources:
          - configmaps
          - deployments
          - events
          - secrets
          - serviceaccounts
        verbs: ["*"]

  roleBindings:
    admin:
      - kind: "Group"
        name: "admins"
    developer:
      - kind: "Group"
        name: "developers"

  networkPolicy:
    allow-dns:
      podSelector:
        matchLabels: {}
      policyTypes:
      - Egress
      egress:
      - to:
        - namespaceSelector:
            matchLabels:
              name: kube-system
        ports:
        - protocol: UDP
          port: 53
    deny-egress:
      podSelector:
        matchLabels: {}
      policyTypes:
        - Egress
    deny-ingress:
      podSelector:
        matchLabels: {}
      policyTypes:
        - Egress
      