apiVersion: project.migrx.io/v1alpha1
kind: ProjectSetTemplate
metadata:
  labels:
    app.kubernetes.io/name: projectsettemplate
    app.kubernetes.io/instance: dev-small2
    app.kubernetes.io/part-of: projectset-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: projectset-operator
  name: dev-mid
spec:

  labels:
    stage: dev-from-template
    env: dev
  annotations:
    app.kubernetes.io/template: dev-mid

  roles:
    developer:
      - apiGroups:
          - ""
          - apps
        resources:
          - configmaps
          - deployments
          - pods
          - pods/log
        verbs: ["*"]

  roleBindings:
    developer:
      - kind: "Group"
        name: "developer"
