apiVersion: project.migrx.io/v1alpha1
kind: ProjectSetTemplate
metadata:
  annotations:
    app.kubernetes.io/name: projectsettemplate
  name: dev-mid
spec:

  labels:
    template: dev-mid
    stage: dev

  annotations:
    app.kubernetes.io/template: dev-mid
    app.kubernetes.io/stage: dev

  resourceQuota:
    hard:
      requests.cpu: "1"
      requests.memory: 1Gi
      limits.cpu: "4"
      limits.memory: 4Gi

  limitRange:
    limits:
      - default:
          cpu: 500m
          memory: "50Mi"
        defaultRequest:
          cpu: 500m
          memory: "50Mi"
        max:
          cpu: "4"
          memory: "4Gi"
        min:
          cpu: 100m
          memory: "50Mi"
        type: Container

  roles:
    developer:
      - apiGroups: ["*"]
        resources: ["*"]
        verbs: ["*"]
    admin:
      - apiGroups:
          - ""
          - apps
        resources:
          - configmaps
          - deployments
          - events
          - secrets
          - serviceaccounts
        verbs: ["*"]

  roleBindings:
    admin:
      - kind: "Group"
        name: "admins"
    developer:
      - kind: "Group"
        name: "developers"

  networkPolicy:
    deny-egress:
      podSelector:
        matchLabels: {}
      policyTypes:
        - Egress
    deny-ingress:
      podSelector:
        matchLabels: {}
      policyTypes:
        - Ingress